config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  devise_for :users, :controllers => {:registrations  => "registrations"}
  root to: 'elections#index'
  get 'ledger', controller: 'pages', action: 'ledger'
  post 'ledger', controller: 'pages', action: 'ledger'
  resources :elections do
    get 'vote/:candidate_id', action: 'vote', as: 'vote'
  end
  resources :candidates
end

app/models/election.rb
class Election < ApplicationRecord
  has_many :nominations
  has_many :votes
  has_many :candidates, through: :nominations

  after_create do
    # Initialize a empty vote count
    Vote.create_genesis_vote(id)
    self.vote_count = {}
    save
  end

  def self.finished
    select { |election| election.voting_over? }
  end

  def nominations_over?
    deadline < DateTime.now
  end

  def voting_over?
    end_time < DateTime.now
  end

  def in_progress?
    DateTime.now.between?(start_time, end_time)
  end

  def nominate(candidate_id)
    Nomination.create(election: self, candidate_id: candidate_id)
    vote_count[candidate_id] = 0
    save
  end

  def vote(voter_id, candidate_id)
    Vote.add_vote(voter_id, candidate_id, id, votes.last)
    vote_count[candidate_id.to_s] += 1
    save
  end

  def winner
    Candidate.find(vote_count.max_by{ |k,v| v }[0])
  end
  
  def to_csv
    require 'csv'
    attributes = %w[hash prev_hash candidate_id]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      votes.each do |vote|
        if vote.vote
          csv << [vote.data, vote.vote.data, vote.candidate_id]
        else
          csv << [vote.data, nil, vote.candidate_id]
        end
      end
    end
  end
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  load_and_authorize_resource
  before_action :set_election, only: [:show, :edit, :update, :destroy]

  # GET /elections
  # GET /elections.json
  def index
    @elections = Election.all
  end

  # GET /elections/1
  # GET /elections/1.json
  def show
    @can_vote = if helpers.voted(@election.id)
                  false
                else
                  (can? :vote, Election) && @election.in_progress?
                end
  end

  # GET /elections/new
  def new
    @election = Election.new
  end

  # GET /elections/1/edit
  def edit
  end

  # POST /elections
  # POST /elections.json
  def create
    @election = Election.new(election_params)

    respond_to do |format|
      if @election.save
        format.html { redirect_to @election, notice: 'Election was successfully created.' }
        format.json { render :show, status: :created, location: @election }
      else
        format.html { render :new }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elections/1
  # PATCH/PUT /elections/1.json
  def update
    respond_to do |format|
      if @election.update(election_params)
        format.html { redirect_to @election, notice: 'Election was successfully updated.' }
        format.json { render :show, status: :ok, location: @election }
      else
        format.html { render :edit }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elections/1
  # DELETE /elections/1.json
  def destroy
    @election.destroy
    respond_to do |format|
      format.html { redirect_to elections_url, notice: 'Election was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    @election = Election.find(params[:election_id])
    @election.vote(@current_user.id, params[:candidate_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_election
      @election = Election.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def election_params
      params.require(:election).permit(:position, :deadline, :start, :end, :session, :vote_count, :candidate_id)
    end
end

app/helpers/elections_helper.rb
module ElectionsHelper
  def voted(election_id)
    election = Election.find(election_id)
    current_user && election.votes.pluck(:user_id).include?(current_user.id)
  end

  def candidates_panel_partial_path(election)
    if election.voting_over?
      'candidate_vote_count'
    else
      'candidates'
    end
  end

  def percent(numerator, denominator)
    (numerator.to_f/denominator)*100
  end
end

app/views/elections/_candidate_vote_count.html.erb
<h3 class="text-center">Election Results</h3>
<br>
<table class="table table-condensed">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Candidate</th>
      <th scope="col">Votes</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% candidates = election.candidates %>
    <% vote_count = election.vote_count.sort_by(&:last).reverse.to_h %>
    <% total_votes = election.votes.count - 1 %>
    <% vote_count.each do |candidate_id, votes| %>
      <% candidate = candidates.find(candidate_id) %>
      <tr>
        <th scope="row">
          <%= link_to candidate.name, candidate_path(candidate) %>
        </th>
        <td><%= votes %></td>
        <td>
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= votes %>" 
                                       aria-valuemin="0" aria-valuemax="<%= total_votes %>" 
                                       style="width: <%= percent(votes, total_votes) %>%;">
              <%= votes %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/elections/_candidates.html.erb
<h3 class="text-center">Nominated Candidates</h3>
<br>

<% if voted(election.id) %>
  <p><strong>You have already voted in this election</strong></p>
<% end %>

<% candidates = election.candidates %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Candidate</th>
      <th scope="col">Affilation</th>
      <th scope="col">Branch</th>
      <th scope="col">Year</th>
      <th scope="col">Course</th>
      <% if @vote %>
        <th scope="col">Vote</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% candidates.each do |candidate| %>
      <tr>
        <th scope="row">
          <%= link_to candidate.name, candidate_path(candidate) %>
        </th>
        <td><%= candidate.affilation %></td>
        <td><%= candidate.branch %></td>
        <td><%= candidate.year %></td>
        <td><%= candidate.course %></td>
        <% if @can_vote %>
          <td>
            <%= link_to 'Vote', election_vote_path(election.id, candidate.id), remote: true %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/elections/_form.html.erb
<%= form_with(model: election, local: true) do |form| %>
  <% if election.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(election.errors.count, "error") %> prohibited this election from being saved:</h2>

      <ul>
      <% election.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div>

  <div class="field">
    <%= form.label :session %>
    <%= form.text_field :session %>
  </div>

  <div class="field">
    <%= form.label :vote_count %>
    <%= form.text_field :vote_count %>
  </div>

  <div class="field">
    <%= form.label :candidate_id %>
    <%= form.text_field :candidate_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elections/edit.html.erb
<h1>Editing Election</h1>

<%= render 'form', election: @election %>

<%= link_to 'Show', @election %> |
<%= link_to 'Back', elections_path %>

app/views/elections/index.html.erb
<%= content_for :title do %>Elections<% end %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Position</th>
      <th scope="col">Session</th>
      <th scope="col">Registration Deadline</th>
      <th scope="col">Voting Start Time</th>
      <th scope="col">Voting End Time</th>
    </tr>
  </thead>

  <tbody>
    <% @elections.each do |election| %>
      <tr>
        <th scope="row">
          <%= link_to election.position, election_path(election) %>
        </th>
        <td><%= election.session %></td>
        <td><%= date_format(election.deadline) %></td>
        <td><%= date_format(election.start_time) %></td>
        <td><%= date_format(election.end_time) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/elections/new.html.erb
<h1>New Election</h1>

<%= render 'form', election: @election %>

<%= link_to 'Back', elections_path %>

app/views/elections/show.html.erb
<%= content_for :title do %><%= @election.position %><% end %>

<p>
  <strong>Deadline:</strong>
  <%= date_format(@election.deadline) %>
</p>

<p>
  <strong>Start:</strong>
  <%= date_format(@election.start_time) %>
</p>

<p>
  <strong>End:</strong>
  <%= date_format(@election.end_time) %>
</p>

<p>
  <strong>Session:</strong>
  <%= @election.session %>
</p>

<% if @election.voting_over? %>
  <p>
    <strong>Winner:</strong>
    <%= link_to @election.winner.name, candidate_path(@election.winner) %>
  </p>
<% end %>

<div id="candidates-panel">
  <%= render partial: candidates_panel_partial_path(@election), locals: {election: @election} %>
</div>

<%= link_to 'Back', elections_path %>

app/views/elections/vote.js.erb
$("#candidates-panel").html('<%= j render partial: 'candidates', locals: {election: @election} %>')